# Generated by Django 5.1 on 2026-01-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
